### ISSUE TITLE
FX bus for delay and reverb

### ISSUE THREAD

**Issue by khoparzi** [samarthgulati/gibber-roll#8]
Add an effects bus for reverb with

`verb = Bus2().fx.add( Freeverb() )`

connect it to the `instrument` with

`var revLevel = 0.5`
`instrument.connect( verb, revLevel )`

revLevel should be controllable by the user

similarly for delay

`delay = Delay({ time:1/6, feedback:.75 })`

and

`var delLevel = 0.5`
`instrument.connect( delay, delLevel )`

**Comment by samarthgulati** [comment]
what happens when one changes the levels? would it have to be re-connected?

**Comment by khoparzi** [comment]
Sorry, the delay had to be

`delay = Bus2().fx.add( Delay({ time:1/6, feedback:.75 }) )`

and then

`instrument.connect( delay, .15 )`

**Comment by khoparzi** [comment]
Okay, slightly new approach

`verb = Bus2().fx.add( Freeverb() )`
`delay = Bus().fx.add( Delay({ time:1/3, feedback:.75,  }) )` as before

but instead of passing just some of the signal to the bus let's send the whole signal with 

`instrument.connect( verb )` and 
`instrument.connect( delay )`

then control the level of reverb and delay with 
`var revLevel = 0.5`
`var delLevel = 0.5`
`verb.gain = revLevel` and
`delay.gain = delLevel`
